### ISSUE TITLE
map drawing

### ISSUE THREAD

**Issue by nonam3e** [nonam3e/game_of_life_wallpaper#4]

**Comment by nonam3e** [comment]
https://dev.to/davidedelpapa/rust-gui-introduction-a-k-a-the-state-of-rust-gui-libraries-as-of-january-2021-40gl

**Comment by WhyHako** [comment]
https://github.com/ragona/draw

**Comment by nonam3e** [comment]
https://github.com/image-rs/image/blob/master/README.md

**Comment by Nedobitaia1** [comment]
https://github.com/danmack/sierpinski-rs/blob/master/src/main.rs
